title: PowerImaginator
description: PowerImaginator generates immersive 3D scenes from text prompts.
theme: just-the-docs
color_scheme: dark
favicon_ico: /assets/img/favicon.png

url: https://powerimaginator.github.io

aux_links:
  Discord: https://discord.gg/Vk3Wh5ZQYD
  GitHub: https://github.com/PowerImaginator
