title: PowerImaginator
description: PowerImaginator generates immersive 3D scenes from text prompts.
favicon_ico: /assets/img/favicon.png
url: https://www.powerimaginator.com
social:
  name: PowerImaginator
  links:
    - https://www.github.com/PowerImaginator
twitter:
  card: summary_large_image

theme: just-the-docs
color_scheme: dark

aux_links:
  Discord: https://discord.gg/Vk3Wh5ZQYD
  GitHub: https://github.com/PowerImaginator

callouts:
  warning:
    title: Warning
    color: red

  note:
    title: Note
    color: green
